-- EnigmaBox demo room (generated by tools/seed-enigma.ts)
-- Idempotent: INSERT OR REPLACE so re-run is safe

INSERT OR REPLACE INTO rooms (id, title, description, creator_id, created_at)
VALUES ('demo-room-1', 'The First Lock', 'A short intro escape. Three quick puzzles to learn how EnigmaBox works.', '00000000-0000-0000-0000-000000000001', '2026-03-02T23:38:53.282Z');

INSERT OR REPLACE INTO puzzles (id, room_id, sequence_order, puzzle_type, content, secret_answer_hash, hints, created_at)
VALUES ('demo-puzzle-1', 'demo-room-1', 0, 'text', 'Welcome. To unlock the next step, answer this: What number comes after 2?', '4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce', '[]', '2026-03-02T23:38:53.282Z');

INSERT OR REPLACE INTO puzzles (id, room_id, sequence_order, puzzle_type, content, secret_answer_hash, hints, created_at)
VALUES ('demo-puzzle-2', 'demo-room-1', 1, 'text', 'Good. Now spell the word that means the opposite of "start".', '361e48d0308f20e32dba5fb56328baf18d72ef0ccb43b84f5c262d2a6a1fc6c8', '["It has three letters."]', '2026-03-02T23:38:53.282Z');

INSERT OR REPLACE INTO puzzles (id, room_id, sequence_order, puzzle_type, content, secret_answer_hash, hints, created_at)
VALUES ('demo-puzzle-3', 'demo-room-1', 2, 'code', 'Final lock. Enter the code: the word "unlock" in all lowercase.', '787600ebe6d6c75b6bc0b2db0bfd6aeec78897b67d3192e2208bc8b714237841', '[]', '2026-03-02T23:38:53.282Z');
