/**
 * Generates apps/web/drizzle/seed_rooms.sql from apps/web/drizzle/seed-data.json.
 * Answer hashes match server/utils/puzzle.ts (SHA-256 of trim+lowercase).
 *
 * Run: pnpm exec tsx tools/seed-enigma.ts
 * Then: wrangler d1 execute enigma-box-db --local --file=apps/web/drizzle/seed_rooms.sql
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const SEED_DATA_PATH = path.join(ROOT, 'apps/web/drizzle/seed-data.json')
const SEED_SQL_PATH = path.join(ROOT, 'apps/web/drizzle/seed_rooms.sql')

function hashAnswer(answer: string): string {
  const normalized = answer.trim().toLowerCase()
  return crypto.createHash('sha256').update(normalized).digest('hex')
}

function escapeSql(s: string): string {
  return s.replace(/'/g, "''")
}

interface SeedData {
  room: {
    id: string
    title: string
    description: string
    creatorId: string
  }
  puzzles: Array<{
    sequenceOrder: number
    puzzleType: string
    content: string
    answer: string
    hints: string[]
  }>
}

async function main() {
  const raw = await fs.readFile(SEED_DATA_PATH, 'utf-8')
  const data = JSON.parse(raw) as SeedData
  const now = new Date().toISOString()

  const lines: string[] = [
    '-- EnigmaBox demo room (generated by tools/seed-enigma.ts)',
    '-- Idempotent: INSERT OR REPLACE so re-run is safe',
    '',
    `INSERT OR REPLACE INTO rooms (id, title, description, creator_id, created_at)`,
    `VALUES ('${escapeSql(data.room.id)}', '${escapeSql(data.room.title)}', '${escapeSql(data.room.description)}', '${escapeSql(data.room.creatorId)}', '${now}');`,
    '',
  ]

  for (const p of data.puzzles) {
    const hash = hashAnswer(p.answer)
    const hintsJson = JSON.stringify(p.hints ?? [])
    const puzzleId = `demo-puzzle-${p.sequenceOrder + 1}`
    lines.push(
      `INSERT OR REPLACE INTO puzzles (id, room_id, sequence_order, puzzle_type, content, secret_answer_hash, hints, created_at)`,
      `VALUES ('${puzzleId}', '${escapeSql(data.room.id)}', ${p.sequenceOrder}, '${escapeSql(p.puzzleType)}', '${escapeSql(p.content)}', '${hash}', '${escapeSql(hintsJson)}', '${now}');`,
      '',
    )
  }

  await fs.writeFile(SEED_SQL_PATH, lines.join('\n'), 'utf-8')
  console.log(`Wrote ${SEED_SQL_PATH}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
